### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by RichardD2** [xceedsoftware/mauitoolkit#1]
The introduction says this library is *"open-source and free"*. But there is no license file in the repository, and no license mentioned anywhere that I can see.

Given Xceed's [previous form for changing licenses retroactively](https://github.com/xceedsoftware/wpftoolkit/issues/1557), this seems like a dangerous oversight.

Is this going to turn into another *"free until we say it isn't"* Xceed project?

**Comment by xceedsoftware** [comment]
The license file was added to our product page. We apologize for the delay as we have just launched the product. To answer your question: the product is free. Is it possible that it will become a commercial product in the future? Yes, that is a possibility. However, the free versions will always remain free. In other words, if we decide to charge for the product in the future, we will release a new version. All our users will be notified in advance, and the versions our users will be currently using will continue to be free as long as when they downloaded it, it was available for free.

**Comment by RichardD2** [comment]
> as long as when they downloaded it, it was available for free

This is precisely why a license is important!

If you release a version under one license, you can't retroactively change the license on that version. Which means *everyone* can continue to use that version for free, regardless of whether or not *the current version* was free when they downloaded it.

But your comment makes it sound like you want to be able to prevent new users from using an old version, or to force them to use it under a different license from the one that applied when it was released.

And by keeping the license on your website, rather than in GitHub where it belongs, you can magically change it at any time without anyone being able to see what it used to be.

**Comment by xceedsoftware** [comment]
We will not make retroactive changes to the license, and we will provide users with advanced warnings when (if) a commercial version is released. I understand your concern, particularly regarding the thread you mentioned, but this will not be the case here. Furthermore, the absence of the license was an oversight, and it has now been included.
