### ISSUE TITLE
Adding modularity to the Library?

### ISSUE THREAD

**Issue by HakamFostok** [xceedsoftware/mauitoolkit#2]
Is there any plan to make the library modular (I mean different Nuget Package for different components)
Maybe someone will need just one component (In my case Chart Control) and nothing else 
Is that will be helpful to the final size of the published App?

Thank you a lot

**Comment by XceedBoucherS** [comment]
Hi @HakamFostok ,
For now, creating many different NuGet packages for the Xceed Maui controls is not in the plan. 
At version v1.5, the NuGet package has a size of 36.6K, it's not that big. So all the controls are in a single package. 
It could change in the future, but at this point, no.

Thank you

**Comment by HakamFostok** [comment]
Ok, I am happy to hear that the library has a very small footprint, that is really encouraging, just a follow-up question
Is Trimming enabled for the DLL, or is there any plans to enable trimming to it

Thank you very much

**Comment by XceedBoucherS** [comment]
Hi,
DLL trimming is currently not enabled since the NuGet package size is relatively low. 
We could consider it in the future, but not for now.
Thank you
